### ISSUE TITLE
Queue Settings is missing in Mautic configuration

### ISSUE THREAD

**Issue by hluchas** [mautic/mautic-documentation#158] opened 2021-01-09 11:07 UTC
I followed [these steps](https://docs.mautic.org/en/queue#rabbitmq) and did not found `Queue Settings` tab in third step.

This needs to be fixed somehow.

**Comment by RCheesley** [comment] 2021-01-09 15:40
Closing as a duplicate of #152

**Closed by RCheesley** 2021-01-09 15:40 UTC
